"""Third-party licence register: generate (`--write`) or check (default).

Reads licences from installed package metadata (Python) and package-lock.json (npm), so entries
are *verified from metadata*, not memory. Check mode fails when a locked dependency is missing
from docs/third-party-licences.md, and when a copyleft-looking licence is not explicitly approved.
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from datetime import date
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "third-party-licences.md"
STRONG = re.compile(r"(?<![A-Za-z])(AGPL|GPL|EUPL|SSPL|CC-BY-SA)", re.I)
WEAK = re.compile(r"(?<![A-Za-z])(LGPL|MPL|EPL|CDDL)|Mozilla Public", re.I)
# Strong copyleft always fails. Weak copyleft (LGPL/MPL) must appear in the register's
# "Pending owner acknowledgement" section (generated) until the owner approves it in
# APPROVED_COPYLEFT (CLAUDE.md §6: copyleft needs owner approval). Approving is NOT done by tooling.
APPROVED_COPYLEFT: dict[str, str] = {}
WORKSPACE = {"geo-common", "geo-backend", "geo-runner", "geo-connectors", "geo-prospecting-platform"}


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def py_licence(name: str) -> str:
    try:
        md = metadata.metadata(name)
    except metadata.PackageNotFoundError:
        return "NOT INSTALLED (platform-specific dependency; licence not verified here)"
    expr = md.get("License-Expression")
    if expr:
        return expr
    lic = (md.get("License") or "").strip()
    if lic and len(lic) < 80 and "\n" not in lic:
        return lic
    classifiers = [c.split("::")[-1].strip() for c in md.get_all("Classifier") or [] if "License" in c]
    return "; ".join(classifiers) or "UNKNOWN"


def python_rows() -> tuple[list[tuple[str, str, str]], list[tuple[str, str, str]]]:
    lock = tomllib.loads((ROOT / "uv.lock").read_text())
    pkgs = {norm(p["name"]): p for p in lock["package"]}

    def closure(roots: list[str]) -> set[str]:
        seen: set[str] = set()
        stack = [norm(r) for r in roots]
        while stack:
            n = stack.pop()
            if n in seen or n not in pkgs:
                continue
            seen.add(n)
            stack += [norm(d["name"]) for d in pkgs[n].get("dependencies", [])]
        return seen

    runtime = closure(["geo-backend", "geo-runner", "geo-common"]) - {norm(w) for w in WORKSPACE}
    dev = set(pkgs) - runtime - {norm(w) for w in WORKSPACE}
    row = lambda n: (pkgs[n]["name"], pkgs[n].get("version", "?"), py_licence(pkgs[n]["name"]))  # noqa: E731
    return [row(n) for n in sorted(runtime)], [row(n) for n in sorted(dev)]


def npm_rows() -> tuple[list[tuple[str, str, str]], list[tuple[str, str, str]]]:
    lock = json.loads((ROOT / "apps/frontend/package-lock.json").read_text())
    runtime, dev = [], []
    for path, info in lock["packages"].items():
        if not path:
            continue
        name = path.split("node_modules/")[-1]
        lic = info.get("license", "UNKNOWN")
        lic = lic if isinstance(lic, str) else json.dumps(lic)
        (dev if info.get("dev") or info.get("devOptional") else runtime).append((name, info["version"], lic))
    return sorted(set(runtime)), sorted(set(dev))


def table(rows: list[tuple[str, str, str]]) -> str:
    return "\n".join(
        ["| Package | Version | Licence |", "|---|---|---|"]
        + [f"| {n} | {v} | {lic} |" for n, v, lic in rows]
    )


def pending(rows: list[tuple[str, str, str]]) -> list[tuple[str, str, str]]:
    return [r for r in rows if WEAK.search(r[2]) and r[0] not in APPROVED_COPYLEFT]


def render() -> str:
    pr, pd = python_rows()
    nr, nd = npm_rows()
    pend = pending(pr + pd + nr + nd)
    return f"""# Third-Party Licence Register

Generated by `scripts/licences.py --write` from installed package metadata and lockfiles
(verified {date.today().isoformat()}). Do not edit by hand. Not legal advice (ADR-0002).
Copyleft entries require explicit owner approval before they may appear in `APPROVED_COPYLEFT`.

## Pending owner acknowledgement (weak copyleft: LGPL/MPL)
Used unmodified as dependencies (no vendored or modified source). Listed so the owner can approve or veto; nothing
here has been approved. Strong copyleft (GPL/AGPL/EUPL/SSPL) is blocked by the check.

{table(pend) if pend else "_none_"}

## Python — runtime (shipped in backend/worker images)
{table(pr)}

## Python — development tooling (not shipped)
{table(pd)}

## npm — runtime (frontend image)
{table(nr)}

## npm — development tooling (not shipped)
{table(nd)}

## Base images and services (not package-managed)
| Component | Used as | Licence (from upstream; re-verify on upgrade) |
|---|---|---|
| python:3.12-slim (Docker official image) | backend/worker base | Python Software Foundation licence + Debian package licences |
| node:22-slim (Docker official image) | frontend base | MIT (Node.js) + Debian package licences |
| postgis/postgis:16-3.4 | database service (separate container, not linked) | PostgreSQL licence; PostGIS GPL-2.0-or-later (separate process) |

Scientific tools (EIS Toolkit, MintPy, pyGIMLi, ResIPy, GPRPy, GemPy) are **not** dependencies yet; see `docs/dependency-strategy.md`.
"""


def main() -> int:
    if "--write" in sys.argv:
        DOC.write_text(render(), encoding="utf-8")
        print(f"wrote {DOC}")
        return 0
    if not DOC.exists():
        print("register missing; run scripts/licences.py --write")
        return 1
    text = DOC.read_text(encoding="utf-8")
    problems = []
    pr, pd = python_rows()
    nr, nd = npm_rows()
    for kind, rows in (("python", pr + pd), ("npm", nr + nd)):
        for name, version, lic in rows:
            if f"| {name} | {version} |" not in text:
                problems.append(f"{kind}: {name} {version} missing from register")
            if STRONG.search(lic) and name not in APPROVED_COPYLEFT:
                problems.append(f"{kind}: {name} strong copyleft licence '{lic}' lacks owner approval")
            if lic == "UNKNOWN":
                problems.append(f"{kind}: {name} licence unknown")
            if (
                WEAK.search(lic)
                and name not in APPROVED_COPYLEFT
                and f"| {name} | {version} | {lic} |" not in text.split("## Python — runtime")[0]
            ):
                problems.append(f"{kind}: {name} weak copyleft not listed under pending acknowledgement")
    for p in problems:
        print(p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
